/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SilenceRouteImport } from './routes/silence'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiGuestSessionRouteImport } from './routes/api/guest-session'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminWebhooksRouteImport } from './routes/admin.webhooks'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminSegmentsRouteImport } from './routes/admin.segments'
import { Route as AdminSafetyRouteImport } from './routes/admin.safety'
import { Route as AdminRetentionRouteImport } from './routes/admin.retention'
import { Route as AdminRecoveryRouteImport } from './routes/admin.recovery'
import { Route as AdminRecoverRouteImport } from './routes/admin.recover'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminMemoryRouteImport } from './routes/admin.memory'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminHeatmapRouteImport } from './routes/admin.heatmap'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminEmotionalRouteImport } from './routes/admin.emotional'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCostRouteImport } from './routes/admin.cost'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAiHealthRouteImport } from './routes/admin.ai-health'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AdminActionsRouteImport } from './routes/admin.actions'
import { Route as AuthenticatedRitualRouteImport } from './routes/_authenticated/ritual'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedMemoriesRouteImport } from './routes/_authenticated/memories'
import { Route as AuthenticatedMandatoryConsentRouteImport } from './routes/_authenticated/mandatory-consent'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AuthenticatedCheckoutPlanRouteImport } from './routes/_authenticated/checkout.$plan'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'
import { Route as ApiPublicJobsWebhookFailureAlertsRouteImport } from './routes/api/public/jobs/webhook-failure-alerts'
import { Route as ApiPublicJobsStaleSessionCleanupRouteImport } from './routes/api/public/jobs/stale-session-cleanup'
import { Route as ApiPublicJobsReengagementDispatchRouteImport } from './routes/api/public/jobs/reengagement-dispatch'
import { Route as ApiPublicJobsRecomputeSegmentsRouteImport } from './routes/api/public/jobs/recompute-segments'
import { Route as ApiPublicJobsPersonalityDriftRouteImport } from './routes/api/public/jobs/personality-drift'
import { Route as ApiPublicJobsPaymentAnomalyDetectionRouteImport } from './routes/api/public/jobs/payment-anomaly-detection'
import { Route as ApiPublicJobsOrphanPaymentReconciliationRouteImport } from './routes/api/public/jobs/orphan-payment-reconciliation'
import { Route as ApiPublicJobsMemoryTtlSweepRouteImport } from './routes/api/public/jobs/memory-ttl-sweep'
import { Route as ApiPublicJobsMemoryConsolidationRouteImport } from './routes/api/public/jobs/memory-consolidation'
import { Route as ApiPublicJobsInactiveDetectionRouteImport } from './routes/api/public/jobs/inactive-detection'
import { Route as ApiPublicJobsGraceExpiryRouteImport } from './routes/api/public/jobs/grace-expiry'
import { Route as ApiPublicJobsFailedPaymentRetryRouteImport } from './routes/api/public/jobs/failed-payment-retry'
import { Route as ApiPublicJobsDailyOpsReportRouteImport } from './routes/api/public/jobs/daily-ops-report'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SilenceRoute = SilenceRouteImport.update({
  id: '/silence',
  path: '/silence',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiGuestSessionRoute = ApiGuestSessionRouteImport.update({
  id: '/api/guest-session',
  path: '/api/guest-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSegmentsRoute = AdminSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSafetyRoute = AdminSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRetentionRoute = AdminRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecoveryRoute = AdminRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecoverRoute = AdminRecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMemoryRoute = AdminMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeatmapRoute = AdminHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmotionalRoute = AdminEmotionalRouteImport.update({
  id: '/emotional',
  path: '/emotional',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCostRoute = AdminCostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiHealthRoute = AdminAiHealthRouteImport.update({
  id: '/ai-health',
  path: '/ai-health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActionsRoute = AdminActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedRitualRoute = AuthenticatedRitualRouteImport.update({
  id: '/ritual',
  path: '/ritual',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMemoriesRoute = AuthenticatedMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMandatoryConsentRoute =
  AuthenticatedMandatoryConsentRouteImport.update({
    id: '/mandatory-consent',
    path: '/mandatory-consent',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AuthenticatedCheckoutPlanRoute =
  AuthenticatedCheckoutPlanRouteImport.update({
    id: '/checkout/$plan',
    path: '/checkout/$plan',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsWebhookFailureAlertsRoute =
  ApiPublicJobsWebhookFailureAlertsRouteImport.update({
    id: '/api/public/jobs/webhook-failure-alerts',
    path: '/api/public/jobs/webhook-failure-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsStaleSessionCleanupRoute =
  ApiPublicJobsStaleSessionCleanupRouteImport.update({
    id: '/api/public/jobs/stale-session-cleanup',
    path: '/api/public/jobs/stale-session-cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsReengagementDispatchRoute =
  ApiPublicJobsReengagementDispatchRouteImport.update({
    id: '/api/public/jobs/reengagement-dispatch',
    path: '/api/public/jobs/reengagement-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsRecomputeSegmentsRoute =
  ApiPublicJobsRecomputeSegmentsRouteImport.update({
    id: '/api/public/jobs/recompute-segments',
    path: '/api/public/jobs/recompute-segments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsPersonalityDriftRoute =
  ApiPublicJobsPersonalityDriftRouteImport.update({
    id: '/api/public/jobs/personality-drift',
    path: '/api/public/jobs/personality-drift',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsPaymentAnomalyDetectionRoute =
  ApiPublicJobsPaymentAnomalyDetectionRouteImport.update({
    id: '/api/public/jobs/payment-anomaly-detection',
    path: '/api/public/jobs/payment-anomaly-detection',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsOrphanPaymentReconciliationRoute =
  ApiPublicJobsOrphanPaymentReconciliationRouteImport.update({
    id: '/api/public/jobs/orphan-payment-reconciliation',
    path: '/api/public/jobs/orphan-payment-reconciliation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsMemoryTtlSweepRoute =
  ApiPublicJobsMemoryTtlSweepRouteImport.update({
    id: '/api/public/jobs/memory-ttl-sweep',
    path: '/api/public/jobs/memory-ttl-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsMemoryConsolidationRoute =
  ApiPublicJobsMemoryConsolidationRouteImport.update({
    id: '/api/public/jobs/memory-consolidation',
    path: '/api/public/jobs/memory-consolidation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsInactiveDetectionRoute =
  ApiPublicJobsInactiveDetectionRouteImport.update({
    id: '/api/public/jobs/inactive-detection',
    path: '/api/public/jobs/inactive-detection',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsGraceExpiryRoute =
  ApiPublicJobsGraceExpiryRouteImport.update({
    id: '/api/public/jobs/grace-expiry',
    path: '/api/public/jobs/grace-expiry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsFailedPaymentRetryRoute =
  ApiPublicJobsFailedPaymentRetryRouteImport.update({
    id: '/api/public/jobs/failed-payment-retry',
    path: '/api/public/jobs/failed-payment-retry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsDailyOpsReportRoute =
  ApiPublicJobsDailyOpsReportRouteImport.update({
    id: '/api/public/jobs/daily-ops-report',
    path: '/api/public/jobs/daily-ops-report',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blocked': typeof BlockedRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/planos': typeof PlanosRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/silence': typeof SilenceRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRoute
  '/mandatory-consent': typeof AuthenticatedMandatoryConsentRoute
  '/memories': typeof AuthenticatedMemoriesRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/ritual': typeof AuthenticatedRitualRoute
  '/admin/actions': typeof AdminActionsRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/ai-health': typeof AdminAiHealthRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/cost': typeof AdminCostRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/emotional': typeof AdminEmotionalRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/heatmap': typeof AdminHeatmapRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/memory': typeof AdminMemoryRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/recover': typeof AdminRecoverRoute
  '/admin/recovery': typeof AdminRecoveryRoute
  '/admin/retention': typeof AdminRetentionRoute
  '/admin/safety': typeof AdminSafetyRoute
  '/admin/segments': typeof AdminSegmentsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
  '/api/guest-session': typeof ApiGuestSessionRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/$plan': typeof AuthenticatedCheckoutPlanRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/jobs/daily-ops-report': typeof ApiPublicJobsDailyOpsReportRoute
  '/api/public/jobs/failed-payment-retry': typeof ApiPublicJobsFailedPaymentRetryRoute
  '/api/public/jobs/grace-expiry': typeof ApiPublicJobsGraceExpiryRoute
  '/api/public/jobs/inactive-detection': typeof ApiPublicJobsInactiveDetectionRoute
  '/api/public/jobs/memory-consolidation': typeof ApiPublicJobsMemoryConsolidationRoute
  '/api/public/jobs/memory-ttl-sweep': typeof ApiPublicJobsMemoryTtlSweepRoute
  '/api/public/jobs/orphan-payment-reconciliation': typeof ApiPublicJobsOrphanPaymentReconciliationRoute
  '/api/public/jobs/payment-anomaly-detection': typeof ApiPublicJobsPaymentAnomalyDetectionRoute
  '/api/public/jobs/personality-drift': typeof ApiPublicJobsPersonalityDriftRoute
  '/api/public/jobs/recompute-segments': typeof ApiPublicJobsRecomputeSegmentsRoute
  '/api/public/jobs/reengagement-dispatch': typeof ApiPublicJobsReengagementDispatchRoute
  '/api/public/jobs/stale-session-cleanup': typeof ApiPublicJobsStaleSessionCleanupRoute
  '/api/public/jobs/webhook-failure-alerts': typeof ApiPublicJobsWebhookFailureAlertsRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocked': typeof BlockedRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/planos': typeof PlanosRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/silence': typeof SilenceRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRoute
  '/mandatory-consent': typeof AuthenticatedMandatoryConsentRoute
  '/memories': typeof AuthenticatedMemoriesRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/ritual': typeof AuthenticatedRitualRoute
  '/admin/actions': typeof AdminActionsRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/ai-health': typeof AdminAiHealthRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/cost': typeof AdminCostRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/emotional': typeof AdminEmotionalRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/heatmap': typeof AdminHeatmapRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/memory': typeof AdminMemoryRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/recover': typeof AdminRecoverRoute
  '/admin/recovery': typeof AdminRecoveryRoute
  '/admin/retention': typeof AdminRetentionRoute
  '/admin/safety': typeof AdminSafetyRoute
  '/admin/segments': typeof AdminSegmentsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
  '/api/guest-session': typeof ApiGuestSessionRoute
  '/admin': typeof AdminIndexRoute
  '/checkout/$plan': typeof AuthenticatedCheckoutPlanRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/jobs/daily-ops-report': typeof ApiPublicJobsDailyOpsReportRoute
  '/api/public/jobs/failed-payment-retry': typeof ApiPublicJobsFailedPaymentRetryRoute
  '/api/public/jobs/grace-expiry': typeof ApiPublicJobsGraceExpiryRoute
  '/api/public/jobs/inactive-detection': typeof ApiPublicJobsInactiveDetectionRoute
  '/api/public/jobs/memory-consolidation': typeof ApiPublicJobsMemoryConsolidationRoute
  '/api/public/jobs/memory-ttl-sweep': typeof ApiPublicJobsMemoryTtlSweepRoute
  '/api/public/jobs/orphan-payment-reconciliation': typeof ApiPublicJobsOrphanPaymentReconciliationRoute
  '/api/public/jobs/payment-anomaly-detection': typeof ApiPublicJobsPaymentAnomalyDetectionRoute
  '/api/public/jobs/personality-drift': typeof ApiPublicJobsPersonalityDriftRoute
  '/api/public/jobs/recompute-segments': typeof ApiPublicJobsRecomputeSegmentsRoute
  '/api/public/jobs/reengagement-dispatch': typeof ApiPublicJobsReengagementDispatchRoute
  '/api/public/jobs/stale-session-cleanup': typeof ApiPublicJobsStaleSessionCleanupRoute
  '/api/public/jobs/webhook-failure-alerts': typeof ApiPublicJobsWebhookFailureAlertsRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/blocked': typeof BlockedRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/planos': typeof PlanosRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/silence': typeof SilenceRoute
  '/terms': typeof TermsRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/mandatory-consent': typeof AuthenticatedMandatoryConsentRoute
  '/_authenticated/memories': typeof AuthenticatedMemoriesRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/ritual': typeof AuthenticatedRitualRoute
  '/admin/actions': typeof AdminActionsRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/ai-health': typeof AdminAiHealthRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/cost': typeof AdminCostRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/emotional': typeof AdminEmotionalRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/heatmap': typeof AdminHeatmapRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/memory': typeof AdminMemoryRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/recover': typeof AdminRecoverRoute
  '/admin/recovery': typeof AdminRecoveryRoute
  '/admin/retention': typeof AdminRetentionRoute
  '/admin/safety': typeof AdminSafetyRoute
  '/admin/segments': typeof AdminSegmentsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
  '/api/guest-session': typeof ApiGuestSessionRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/checkout/$plan': typeof AuthenticatedCheckoutPlanRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/jobs/daily-ops-report': typeof ApiPublicJobsDailyOpsReportRoute
  '/api/public/jobs/failed-payment-retry': typeof ApiPublicJobsFailedPaymentRetryRoute
  '/api/public/jobs/grace-expiry': typeof ApiPublicJobsGraceExpiryRoute
  '/api/public/jobs/inactive-detection': typeof ApiPublicJobsInactiveDetectionRoute
  '/api/public/jobs/memory-consolidation': typeof ApiPublicJobsMemoryConsolidationRoute
  '/api/public/jobs/memory-ttl-sweep': typeof ApiPublicJobsMemoryTtlSweepRoute
  '/api/public/jobs/orphan-payment-reconciliation': typeof ApiPublicJobsOrphanPaymentReconciliationRoute
  '/api/public/jobs/payment-anomaly-detection': typeof ApiPublicJobsPaymentAnomalyDetectionRoute
  '/api/public/jobs/personality-drift': typeof ApiPublicJobsPersonalityDriftRoute
  '/api/public/jobs/recompute-segments': typeof ApiPublicJobsRecomputeSegmentsRoute
  '/api/public/jobs/reengagement-dispatch': typeof ApiPublicJobsReengagementDispatchRoute
  '/api/public/jobs/stale-session-cleanup': typeof ApiPublicJobsStaleSessionCleanupRoute
  '/api/public/jobs/webhook-failure-alerts': typeof ApiPublicJobsWebhookFailureAlertsRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blocked'
    | '/contato'
    | '/login'
    | '/maintenance'
    | '/planos'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/silence'
    | '/terms'
    | '/app'
    | '/mandatory-consent'
    | '/memories'
    | '/plans'
    | '/profile'
    | '/ritual'
    | '/admin/actions'
    | '/admin/admins'
    | '/admin/ai-health'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/cost'
    | '/admin/dashboard'
    | '/admin/emotional'
    | '/admin/health'
    | '/admin/heatmap'
    | '/admin/login'
    | '/admin/memory'
    | '/admin/plans'
    | '/admin/recover'
    | '/admin/recovery'
    | '/admin/retention'
    | '/admin/safety'
    | '/admin/segments'
    | '/admin/system'
    | '/admin/users'
    | '/admin/webhooks'
    | '/api/chat'
    | '/api/contact'
    | '/api/guest-session'
    | '/admin/'
    | '/checkout/$plan'
    | '/admin/users/$userId'
    | '/api/public/health'
    | '/api/public/jobs/daily-ops-report'
    | '/api/public/jobs/failed-payment-retry'
    | '/api/public/jobs/grace-expiry'
    | '/api/public/jobs/inactive-detection'
    | '/api/public/jobs/memory-consolidation'
    | '/api/public/jobs/memory-ttl-sweep'
    | '/api/public/jobs/orphan-payment-reconciliation'
    | '/api/public/jobs/payment-anomaly-detection'
    | '/api/public/jobs/personality-drift'
    | '/api/public/jobs/recompute-segments'
    | '/api/public/jobs/reengagement-dispatch'
    | '/api/public/jobs/stale-session-cleanup'
    | '/api/public/jobs/webhook-failure-alerts'
    | '/api/public/webhooks/mercadopago'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocked'
    | '/contato'
    | '/login'
    | '/maintenance'
    | '/planos'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/silence'
    | '/terms'
    | '/app'
    | '/mandatory-consent'
    | '/memories'
    | '/plans'
    | '/profile'
    | '/ritual'
    | '/admin/actions'
    | '/admin/admins'
    | '/admin/ai-health'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/cost'
    | '/admin/dashboard'
    | '/admin/emotional'
    | '/admin/health'
    | '/admin/heatmap'
    | '/admin/login'
    | '/admin/memory'
    | '/admin/plans'
    | '/admin/recover'
    | '/admin/recovery'
    | '/admin/retention'
    | '/admin/safety'
    | '/admin/segments'
    | '/admin/system'
    | '/admin/users'
    | '/admin/webhooks'
    | '/api/chat'
    | '/api/contact'
    | '/api/guest-session'
    | '/admin'
    | '/checkout/$plan'
    | '/admin/users/$userId'
    | '/api/public/health'
    | '/api/public/jobs/daily-ops-report'
    | '/api/public/jobs/failed-payment-retry'
    | '/api/public/jobs/grace-expiry'
    | '/api/public/jobs/inactive-detection'
    | '/api/public/jobs/memory-consolidation'
    | '/api/public/jobs/memory-ttl-sweep'
    | '/api/public/jobs/orphan-payment-reconciliation'
    | '/api/public/jobs/payment-anomaly-detection'
    | '/api/public/jobs/personality-drift'
    | '/api/public/jobs/recompute-segments'
    | '/api/public/jobs/reengagement-dispatch'
    | '/api/public/jobs/stale-session-cleanup'
    | '/api/public/jobs/webhook-failure-alerts'
    | '/api/public/webhooks/mercadopago'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/blocked'
    | '/contato'
    | '/login'
    | '/maintenance'
    | '/planos'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/silence'
    | '/terms'
    | '/_authenticated/app'
    | '/_authenticated/mandatory-consent'
    | '/_authenticated/memories'
    | '/_authenticated/plans'
    | '/_authenticated/profile'
    | '/_authenticated/ritual'
    | '/admin/actions'
    | '/admin/admins'
    | '/admin/ai-health'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/cost'
    | '/admin/dashboard'
    | '/admin/emotional'
    | '/admin/health'
    | '/admin/heatmap'
    | '/admin/login'
    | '/admin/memory'
    | '/admin/plans'
    | '/admin/recover'
    | '/admin/recovery'
    | '/admin/retention'
    | '/admin/safety'
    | '/admin/segments'
    | '/admin/system'
    | '/admin/users'
    | '/admin/webhooks'
    | '/api/chat'
    | '/api/contact'
    | '/api/guest-session'
    | '/admin/'
    | '/_authenticated/checkout/$plan'
    | '/admin/users/$userId'
    | '/api/public/health'
    | '/api/public/jobs/daily-ops-report'
    | '/api/public/jobs/failed-payment-retry'
    | '/api/public/jobs/grace-expiry'
    | '/api/public/jobs/inactive-detection'
    | '/api/public/jobs/memory-consolidation'
    | '/api/public/jobs/memory-ttl-sweep'
    | '/api/public/jobs/orphan-payment-reconciliation'
    | '/api/public/jobs/payment-anomaly-detection'
    | '/api/public/jobs/personality-drift'
    | '/api/public/jobs/recompute-segments'
    | '/api/public/jobs/reengagement-dispatch'
    | '/api/public/jobs/stale-session-cleanup'
    | '/api/public/jobs/webhook-failure-alerts'
    | '/api/public/webhooks/mercadopago'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  BlockedRoute: typeof BlockedRoute
  ContatoRoute: typeof ContatoRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PlanosRoute: typeof PlanosRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SilenceRoute: typeof SilenceRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiGuestSessionRoute: typeof ApiGuestSessionRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicJobsDailyOpsReportRoute: typeof ApiPublicJobsDailyOpsReportRoute
  ApiPublicJobsFailedPaymentRetryRoute: typeof ApiPublicJobsFailedPaymentRetryRoute
  ApiPublicJobsGraceExpiryRoute: typeof ApiPublicJobsGraceExpiryRoute
  ApiPublicJobsInactiveDetectionRoute: typeof ApiPublicJobsInactiveDetectionRoute
  ApiPublicJobsMemoryConsolidationRoute: typeof ApiPublicJobsMemoryConsolidationRoute
  ApiPublicJobsMemoryTtlSweepRoute: typeof ApiPublicJobsMemoryTtlSweepRoute
  ApiPublicJobsOrphanPaymentReconciliationRoute: typeof ApiPublicJobsOrphanPaymentReconciliationRoute
  ApiPublicJobsPaymentAnomalyDetectionRoute: typeof ApiPublicJobsPaymentAnomalyDetectionRoute
  ApiPublicJobsPersonalityDriftRoute: typeof ApiPublicJobsPersonalityDriftRoute
  ApiPublicJobsRecomputeSegmentsRoute: typeof ApiPublicJobsRecomputeSegmentsRoute
  ApiPublicJobsReengagementDispatchRoute: typeof ApiPublicJobsReengagementDispatchRoute
  ApiPublicJobsStaleSessionCleanupRoute: typeof ApiPublicJobsStaleSessionCleanupRoute
  ApiPublicJobsWebhookFailureAlertsRoute: typeof ApiPublicJobsWebhookFailureAlertsRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/silence': {
      id: '/silence'
      path: '/silence'
      fullPath: '/silence'
      preLoaderRoute: typeof SilenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/guest-session': {
      id: '/api/guest-session'
      path: '/api/guest-session'
      fullPath: '/api/guest-session'
      preLoaderRoute: typeof ApiGuestSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/webhooks': {
      id: '/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/segments': {
      id: '/admin/segments'
      path: '/segments'
      fullPath: '/admin/segments'
      preLoaderRoute: typeof AdminSegmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/safety': {
      id: '/admin/safety'
      path: '/safety'
      fullPath: '/admin/safety'
      preLoaderRoute: typeof AdminSafetyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/retention': {
      id: '/admin/retention'
      path: '/retention'
      fullPath: '/admin/retention'
      preLoaderRoute: typeof AdminRetentionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recovery': {
      id: '/admin/recovery'
      path: '/recovery'
      fullPath: '/admin/recovery'
      preLoaderRoute: typeof AdminRecoveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recover': {
      id: '/admin/recover'
      path: '/recover'
      fullPath: '/admin/recover'
      preLoaderRoute: typeof AdminRecoverRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/memory': {
      id: '/admin/memory'
      path: '/memory'
      fullPath: '/admin/memory'
      preLoaderRoute: typeof AdminMemoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/heatmap': {
      id: '/admin/heatmap'
      path: '/heatmap'
      fullPath: '/admin/heatmap'
      preLoaderRoute: typeof AdminHeatmapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emotional': {
      id: '/admin/emotional'
      path: '/emotional'
      fullPath: '/admin/emotional'
      preLoaderRoute: typeof AdminEmotionalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cost': {
      id: '/admin/cost'
      path: '/cost'
      fullPath: '/admin/cost'
      preLoaderRoute: typeof AdminCostRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-health': {
      id: '/admin/ai-health'
      path: '/ai-health'
      fullPath: '/admin/ai-health'
      preLoaderRoute: typeof AdminAiHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/actions': {
      id: '/admin/actions'
      path: '/actions'
      fullPath: '/admin/actions'
      preLoaderRoute: typeof AdminActionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/ritual': {
      id: '/_authenticated/ritual'
      path: '/ritual'
      fullPath: '/ritual'
      preLoaderRoute: typeof AuthenticatedRitualRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/memories': {
      id: '/_authenticated/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof AuthenticatedMemoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mandatory-consent': {
      id: '/_authenticated/mandatory-consent'
      path: '/mandatory-consent'
      fullPath: '/mandatory-consent'
      preLoaderRoute: typeof AuthenticatedMandatoryConsentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/_authenticated/checkout/$plan': {
      id: '/_authenticated/checkout/$plan'
      path: '/checkout/$plan'
      fullPath: '/checkout/$plan'
      preLoaderRoute: typeof AuthenticatedCheckoutPlanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/webhook-failure-alerts': {
      id: '/api/public/jobs/webhook-failure-alerts'
      path: '/api/public/jobs/webhook-failure-alerts'
      fullPath: '/api/public/jobs/webhook-failure-alerts'
      preLoaderRoute: typeof ApiPublicJobsWebhookFailureAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/stale-session-cleanup': {
      id: '/api/public/jobs/stale-session-cleanup'
      path: '/api/public/jobs/stale-session-cleanup'
      fullPath: '/api/public/jobs/stale-session-cleanup'
      preLoaderRoute: typeof ApiPublicJobsStaleSessionCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/reengagement-dispatch': {
      id: '/api/public/jobs/reengagement-dispatch'
      path: '/api/public/jobs/reengagement-dispatch'
      fullPath: '/api/public/jobs/reengagement-dispatch'
      preLoaderRoute: typeof ApiPublicJobsReengagementDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/recompute-segments': {
      id: '/api/public/jobs/recompute-segments'
      path: '/api/public/jobs/recompute-segments'
      fullPath: '/api/public/jobs/recompute-segments'
      preLoaderRoute: typeof ApiPublicJobsRecomputeSegmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/personality-drift': {
      id: '/api/public/jobs/personality-drift'
      path: '/api/public/jobs/personality-drift'
      fullPath: '/api/public/jobs/personality-drift'
      preLoaderRoute: typeof ApiPublicJobsPersonalityDriftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/payment-anomaly-detection': {
      id: '/api/public/jobs/payment-anomaly-detection'
      path: '/api/public/jobs/payment-anomaly-detection'
      fullPath: '/api/public/jobs/payment-anomaly-detection'
      preLoaderRoute: typeof ApiPublicJobsPaymentAnomalyDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/orphan-payment-reconciliation': {
      id: '/api/public/jobs/orphan-payment-reconciliation'
      path: '/api/public/jobs/orphan-payment-reconciliation'
      fullPath: '/api/public/jobs/orphan-payment-reconciliation'
      preLoaderRoute: typeof ApiPublicJobsOrphanPaymentReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/memory-ttl-sweep': {
      id: '/api/public/jobs/memory-ttl-sweep'
      path: '/api/public/jobs/memory-ttl-sweep'
      fullPath: '/api/public/jobs/memory-ttl-sweep'
      preLoaderRoute: typeof ApiPublicJobsMemoryTtlSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/memory-consolidation': {
      id: '/api/public/jobs/memory-consolidation'
      path: '/api/public/jobs/memory-consolidation'
      fullPath: '/api/public/jobs/memory-consolidation'
      preLoaderRoute: typeof ApiPublicJobsMemoryConsolidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/inactive-detection': {
      id: '/api/public/jobs/inactive-detection'
      path: '/api/public/jobs/inactive-detection'
      fullPath: '/api/public/jobs/inactive-detection'
      preLoaderRoute: typeof ApiPublicJobsInactiveDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/grace-expiry': {
      id: '/api/public/jobs/grace-expiry'
      path: '/api/public/jobs/grace-expiry'
      fullPath: '/api/public/jobs/grace-expiry'
      preLoaderRoute: typeof ApiPublicJobsGraceExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/failed-payment-retry': {
      id: '/api/public/jobs/failed-payment-retry'
      path: '/api/public/jobs/failed-payment-retry'
      fullPath: '/api/public/jobs/failed-payment-retry'
      preLoaderRoute: typeof ApiPublicJobsFailedPaymentRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/daily-ops-report': {
      id: '/api/public/jobs/daily-ops-report'
      path: '/api/public/jobs/daily-ops-report'
      fullPath: '/api/public/jobs/daily-ops-report'
      preLoaderRoute: typeof ApiPublicJobsDailyOpsReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedMandatoryConsentRoute: typeof AuthenticatedMandatoryConsentRoute
  AuthenticatedMemoriesRoute: typeof AuthenticatedMemoriesRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRitualRoute: typeof AuthenticatedRitualRoute
  AuthenticatedCheckoutPlanRoute: typeof AuthenticatedCheckoutPlanRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedMandatoryConsentRoute: AuthenticatedMandatoryConsentRoute,
  AuthenticatedMemoriesRoute: AuthenticatedMemoriesRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRitualRoute: AuthenticatedRitualRoute,
  AuthenticatedCheckoutPlanRoute: AuthenticatedCheckoutPlanRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminActionsRoute: typeof AdminActionsRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAiHealthRoute: typeof AdminAiHealthRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCostRoute: typeof AdminCostRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmotionalRoute: typeof AdminEmotionalRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminHeatmapRoute: typeof AdminHeatmapRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMemoryRoute: typeof AdminMemoryRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminRecoverRoute: typeof AdminRecoverRoute
  AdminRecoveryRoute: typeof AdminRecoveryRoute
  AdminRetentionRoute: typeof AdminRetentionRoute
  AdminSafetyRoute: typeof AdminSafetyRoute
  AdminSegmentsRoute: typeof AdminSegmentsRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActionsRoute: AdminActionsRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAiHealthRoute: AdminAiHealthRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminCostRoute: AdminCostRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmotionalRoute: AdminEmotionalRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminHeatmapRoute: AdminHeatmapRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMemoryRoute: AdminMemoryRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminRecoverRoute: AdminRecoverRoute,
  AdminRecoveryRoute: AdminRecoveryRoute,
  AdminRetentionRoute: AdminRetentionRoute,
  AdminSafetyRoute: AdminSafetyRoute,
  AdminSegmentsRoute: AdminSegmentsRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminWebhooksRoute: AdminWebhooksRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  BlockedRoute: BlockedRoute,
  ContatoRoute: ContatoRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  PlanosRoute: PlanosRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SilenceRoute: SilenceRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiContactRoute: ApiContactRoute,
  ApiGuestSessionRoute: ApiGuestSessionRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicJobsDailyOpsReportRoute: ApiPublicJobsDailyOpsReportRoute,
  ApiPublicJobsFailedPaymentRetryRoute: ApiPublicJobsFailedPaymentRetryRoute,
  ApiPublicJobsGraceExpiryRoute: ApiPublicJobsGraceExpiryRoute,
  ApiPublicJobsInactiveDetectionRoute: ApiPublicJobsInactiveDetectionRoute,
  ApiPublicJobsMemoryConsolidationRoute: ApiPublicJobsMemoryConsolidationRoute,
  ApiPublicJobsMemoryTtlSweepRoute: ApiPublicJobsMemoryTtlSweepRoute,
  ApiPublicJobsOrphanPaymentReconciliationRoute:
    ApiPublicJobsOrphanPaymentReconciliationRoute,
  ApiPublicJobsPaymentAnomalyDetectionRoute:
    ApiPublicJobsPaymentAnomalyDetectionRoute,
  ApiPublicJobsPersonalityDriftRoute: ApiPublicJobsPersonalityDriftRoute,
  ApiPublicJobsRecomputeSegmentsRoute: ApiPublicJobsRecomputeSegmentsRoute,
  ApiPublicJobsReengagementDispatchRoute:
    ApiPublicJobsReengagementDispatchRoute,
  ApiPublicJobsStaleSessionCleanupRoute: ApiPublicJobsStaleSessionCleanupRoute,
  ApiPublicJobsWebhookFailureAlertsRoute:
    ApiPublicJobsWebhookFailureAlertsRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
